---
# Apply latest Ruby style guide and newly introduced cops
AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  Include:
    - 'Gemfile'
    - 'Rakefile'
    - '**/*.rb'
  Exclude:
    - '_snippets/**/*'